### ISSUE TITLE
dpvs base on dpdk 1.6 is not working 

### ISSUE THREAD

**Issue by aaronwme** [iqiyi/dpvs#16] opened 2017-10-19 04:44 UTC
EAL: Error - exiting with code: 1
  Cause: add KNI port fail, exiting...

**Comment by mscbg** [comment] 2017-10-19 04:50
check whether kni is loaded by command "lsmod|grep rte_kni"

**Comment by aaronwme** [comment] 2017-10-19 05:12
[root@localhost bin]# lsmod | grep rte_kni
rte_kni               298507  0
i2c_core               40325  6 drm,i2c_i801,rte_kni,drm_kms_helper,mgag200,i2c_algo_bit
[root@localhost bin]# ./dpdk-devbind.py --st
Network devices using DPDK-compatible driver
============================================
0000:05:00.0 '82599ES 10-Gigabit SFI/SFP+ Network Connection' drv=igb_uio unused=

 /var/log/message same as /var/log/dpvs.log

EAL: Detected 16 lcore(s)
EAL: Probing VFIO support...
PMD: bnxt_rte_pmd_init() called for (null)
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
EAL: PCI device 0000:05:00.1 on NUMA socket 0
EAL:   probe driver: 8086:10fb rte_ixgbe_pmd
CFG_FILE: Opening configuration file '/etc/dpvs.conf'.
CFG_FILE: log_level = WARNING
NETIF: dpdk0:rx_queue_number = 8
NETIF: worker cpu1:dpdk0 rx_queue_id += 0
NETIF: worker cpu1:dpdk0 tx_queue_id += 0
NETIF: worker cpu2:dpdk0 rx_queue_id += 1
NETIF: worker cpu2:dpdk0 tx_queue_id += 1
NETIF: worker cpu3:dpdk0 rx_queue_id += 2
NETIF: worker cpu3:dpdk0 tx_queue_id += 2
NETIF: worker cpu4:dpdk0 rx_queue_id += 3
NETIF: worker cpu4:dpdk0 tx_queue_id += 3
NETIF: worker cpu5:dpdk0 rx_queue_id += 4
NETIF: worker cpu5:dpdk0 tx_queue_id += 4
NETIF: worker cpu6:dpdk0 rx_queue_id += 5
NETIF: worker cpu6:dpdk0 tx_queue_id += 5
NETIF: worker cpu7:dpdk0 rx_queue_id += 6
NETIF: worker cpu7:dpdk0 tx_queue_id += 6
NETIF: worker cpu8:dpdk0 rx_queue_id += 7
NETIF: worker cpu8:dpdk0 tx_queue_id += 7
EAL: Error - exiting with code: 1
  Cause: add KNI port fail, exiting...

**Comment by ywc689** [comment] 2017-10-19 06:04
Did you use the dpvs.conf.single-nic.sample  cfgfile  and bind only one NIC to igb_uio driver ?
You could gdb the kni.c:kni_add_dev and find out where the problem is.

**Comment by aaronwme** [comment] 2017-10-19 06:17
use the dpvs.conf.single-nic.sample cfgfile

**Comment by aaronwme** [comment] 2017-10-19 08:00
fix,dpdk 1.6 not support the 10Gb device

**Comment by ywc689** [comment] 2017-10-19 09:43
pls use dpdk-16.07, other dpdk versions not tested yet. We would test dpvs on dpdk-17.05 soon.

**Comment by beacer** [comment] 2017-10-20 02:05
@aaronwme, is it works on 16.07 now ?

**Comment by aaronwme** [comment] 2017-10-20 02:18
@beacer no,16.07 is not support the 10Gb device。wait for base on dpdk 1.7

**Comment by beacer** [comment] 2017-10-20 03:04
@aaronwme 16.07 works for 10Gb NIC, the NIC we're using (Intel X540 ) is exactly 10G.
`Ethernet controller: Intel Corporation Ethernet Controller 10-Gigabit X540-AT2 (rev 01)`
And your NIC **`82599ES` is also in 16.07's tested device list**. http://dpdk.org/doc/guides/rel_notes/release_16_07.html

**Comment by Shadowu410** [comment] 2017-10-23 07:08
The same problem with DPDK 16.07 in vmware VM（2 vmxnet3 nics），but successfully run the kni sample offered in dpdk source with "./kni -c f -n 4 -- -p 0x3 --config="(0,0,2),(1,1,3)"" and captured some packet with tcpdump.

**Comment by aaronwme** [comment] 2017-11-06 15:17
fix it !memlock is not config

**Comment by aaronwme** [comment] 2017-11-06 15:25
@beacer  Can you give me an example for kni 。 I set ip addr to the dpdk0.kni，But packet 100% lost when I ping the ip addr .Thanks alot

**Comment by beacer** [comment] 2017-11-07 03:05
@aaronwme we're writing the config examples, including `kni` devices, and also `FNAT`, `DR`, `SNAT`, `keepalived`/`ospfd`, etc.  Will release the doc later this week.

**Comment by aaronwme** [comment] 2017-11-07 10:41
@beacer expecting ：）

**Comment by beacer** [comment] 2017-11-09 07:30
@aaronwme  pls follow `doc/tutorial.md` for example of `KNI`. And I'll close this issue, since it's fixed.

**Closed by beacer** 2017-11-09 07:30 UTC

**Comment by aaronwme** [comment] 2017-11-09 12:26
@beacer Thank you very much!!!

**Comment by aaronwme** [comment] 2017-11-09 13:34
@beacer the example file 
`./dpip route add 172.10.0.2/30 dev dpdk1 scope kni_host`

kni_host is paramter or kni device name such as dpdk0.kni ?
But no matter what kind of situation ,ping packet 100% lost 

if kni_host is paramter the result like this 

[[sockopt_msg_recv] errcode set in socket msg#300 header: invalid parameter(-1)
dpip: invalid parameter]

Looking forward to your reply!!!

**Comment by beacer** [comment] 2017-11-10 01:38
This the option name, not the interface name. `kni_host` means routing the packet to `kni` devices.
Pls show the log of `./dpip route show`, `./dpip addr show`, `./dpip link show`.

**Comment by aaronwme** [comment] 2017-11-10 03:29
```
[root@localhost bin]# ./dpip link show
1: dpdk0: socket 0 mtu 1500 rx-queue 8 tx-queue 8
    UP 10000 Mbps full-duplex fixed-nego promisc-off
    addr 14:02:EC:95:0E:58 OF_RX_IP_CSUM OF_TX_IP_CSUM OF_TX_TCP_CSUM OF_TX_UDP_CSUM
[root@localhost bin]# ./dpip addr show
[root@localhost bin]# ./dpip route show
[root@localhost bin]# ./dpip route add 111.13.134.155/25 dev dpdk0 scope kni_host
[sockopt_msg_recv] errcode set in socket msg#300 header: invalid parameter(-1)
dpip: invalid parameter
[root@localhost bin]#
```

**Comment by beacer** [comment] 2017-11-10 03:39
the prefix length of `scope kni_host` route must be 32.
```
# ./dpip route add 111.13.134.155/25 dev dpdk0 scope kni_host
# ./dpip route show
inet 111.13.134.155/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope kni_host metric 0 proto auto
```

**Comment by aaronwme** [comment] 2017-11-10 06:07
I'm sorry,I need your help!Where I configured wrong？
```
[root@localhost bin]# ./dpip link show
1: dpdk0: socket 0 mtu 1500 rx-queue 8 tx-queue 8
    UP 10000 Mbps full-duplex fixed-nego promisc-off
    addr 14:02:EC:95:0E:58 OF_RX_IP_CSUM OF_TX_IP_CSUM OF_TX_TCP_CSUM OF_TX_UDP_CSUM
[root@localhost bin]# ./dpip addr show
[root@localhost bin]# ./dpip route show
inet 111.13.134.155/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope kni_host metric 0 proto auto
[root@localhost bin]# ip link show dev dpdk0.kni
32: dpdk0.kni: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT qlen 1000
    link/ether 14:02:ec:95:0e:58 brd ff:ff:ff:ff:ff:ff
[root@localhost bin]# ip addr show dev dpdk0.kni
32: dpdk0.kni: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN qlen 1000
    link/ether 14:02:ec:95:0e:58 brd ff:ff:ff:ff:ff:ff
    inet 111.13.134.155/25 scope global dpdk0.kni
       valid_lft forever preferred_lft forever
    inet6 fe80::1602:ecff:fe95:e58/64 scope link
       valid_lft forever preferred_lft forever
[root@localhost bin]# ip route show dev dpdk0.kni
default via 111.13.134.129
111.13.134.128/25  proto kernel  scope link  src 111.13.134.155
[root@localhost bin]# ping -c 1 111.13.134.129
PING 111.13.134.129 (111.13.134.129) 56(84) bytes of data.
From 111.13.134.155 icmp_seq=1 Destination Host Unreachable

--- 111.13.134.129 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

[root@localhost bin]#
```

**Comment by beacer** [comment] 2017-11-10 06:45
add another route without kni_host,
```
dpip route add 111.13.134.155/32 dev dpdk0 scope kni_host
dpip route add 111.13.134.155/25 dev dpdk0
```

**Comment by aaronwme** [comment] 2017-11-10 07:33
`[root@localhost bin]# ./dpip -s route show
inet 111.13.134.155/32 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope kni_host metric 0 proto auto
inet 111.13.134.155/25 via 0.0.0.0 src 0.0.0.0 dev dpdk0 mtu 1500 tos 0 scope link metric 0 proto auto
[root@localhost bin]# ping -c 1 111.13.134.129
PING 111.13.134.129 (111.13.134.129) 56(84) bytes of data.
From 111.13.134.155 icmp_seq=1 Destination Host Unreachable

--- 111.13.134.129 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms`

**Comment by aaronwme** [comment] 2017-11-17 03:17
@beacer help me!!!
