### ISSUE TITLE
It takes too long to recover when delete UDP RS with ipvsadm

### ISSUE THREAD

**Issue by icymoon** [iqiyi/dpvs#109] opened 2018-01-24 04:05 UTC
0. config dpvs with at least two DNS real servers
1. run this command on client: 
 while [ 1 ]; do dig tdomain.cn @x.x.x.x > /dev/null 2>&1; echo -n $? ; done
It print 00000....
2. delete 1 DNS real server with ipvsadm -d
command on client will print several 9...which indicates fail.
waiting until it all print 0 again.
It takes at least 1 min...I think it's too long...

**Comment by ywc689** [comment] 2018-01-25 06:22
The default dpvs UDP connection timeout  is 300s. If dig issues 2 dns querry with the same source IP and port in 300s, the second querry would reuse the previous dpvs connection, i.e. the incarnation of previous connection. And if RS of this connection is removed at the time between the 2 querries, the second querry would fail because the RS of the connection is not available.

The problem is related both to client behaviors and dpvs connection timeout. To avoid this problem, you can:
1. decrease the dpvs udp connection timeout(dpvs.conf: ipvs_defs>udp>timeout>normal)
2. let client use more source IP/source port to querry the service.
```
12:47:33.674838 IP 192.168.37.23.42334 > 192.168.4.100.53: 45423+ A? www.baidu.com. (31)
12:47:33.724187 IP 192.168.4.100.53 > 192.168.37.23.42334: 45423 3/5/5 CNAME www.a.shifen.com., A 115.239.211.112, A 115.239.210.27 (260)
12:51:09.360823 IP 192.168.37.23.42334 > 192.168.4.100.53: 47662+ A? www.baidu.com. (31)
12:51:14.360964 IP 192.168.37.23.42334 > 192.168.4.100.53: 47662+ A? www.baidu.com. (31)
12:51:19.361156 IP 192.168.37.23.42334 > 192.168.4.100.53: 47662+ A? www.baidu.com. (31)

12:48:08.482146 IP 192.168.37.23.53299 > 192.168.4.100.53: 18632+ A? www.baidu.com. (31)
12:48:08.531518 IP 192.168.4.100.53 > 192.168.37.23.53299: 18632 3/5/5 CNAME www.a.shifen.com., A 115.239.210.27, A 115.239.211.112 (260)
12:51:41.095062 IP 192.168.37.23.53299 > 192.168.4.100.53: 38393+ A? www.baidu.com. (31)
12:51:46.095168 IP 192.168.37.23.53299 > 192.168.4.100.53: 38393+ A? www.baidu.com. (31)
12:51:51.095332 IP 192.168.37.23.53299 > 192.168.4.100.53: 38393+ A? www.baidu.com. (31)
```

**Comment by beacer** [comment] 2018-01-26 05:35
Hi @icymoon, just as @ywc689  said, it's because client's *source port* is reused within the UDP connection timeout (default is 300s). The pkt hit the connection entry and be forwarded to RS which is already removed.
1. Note when removing RS, existing connection related to that RS should not be removed, otherwise 'long-time' connection will get abort unexpected. RS is removed from LB not means it won't work. On the other hand, UDP is stateless, we can only 5-tuple to determine if pkt belongs to same "connection".
2. In real world, the client will not initial the connection (TCP/UDP) that fast, and the client should reuse it's local port after a longer time.
For the reason above, I'll close the issue, if you think it's still an issue, you can reopen it and let's discuss further.

**Closed by beacer** 2018-01-26 05:35 UTC
